name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: deps
      run: sudo apt-get install gtk-doc-tools gobject-introspection libcroco3-dev libpango1.0-dev libgdk-pixbuf-2.0-dev libgtk-3-dev
    - uses: actions/checkout@v3
    - name: bootstrap
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck
